name: mysponsors
description: Library to fetch my sponsors information.
version: 0.1.0
repository: https://github.com/alexrintt/mysponsors.dart

environment:
  sdk: ^3.1.2

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
